apiVersion: oda.tmforum.org/v1alpha4
kind: component
metadata:
  name: r1-ericsson-pim
  labels:
    oda.tmforum.org/componentName: r1-ericsson-pim
spec:
  type: TMFC005-productinventorymanagement
  selector:
    matchLabels:
     oda.tmforum.org/componentName: r1-ericsson-pim
  componentKinds:
  - group: core
    kind: Service    
  - group: core
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment  
  version: "0.0.1"
  description: "Simple Product Inventory Managment Adapter ODA-Component from Open-API reference implementation." 
  maintainers:
  - name: Dinesh Kumar
    email: g.dinesh.kumar@ericsson.com
  owners:
    - name: Dinesh Kumar
      email: g.dinesh.kumar@ericsson.com 
  coreFunction:
    exposedAPIs: 
    - name: pimadapter
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF637_ProductInventory/master/TMF637-ProductInventory-v4.0.0.swagger.json
      implementation: r1-prodinventoryapi
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/pimadapter/v4/
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/pimadapter/v4/api-docs
      port: 8080 
    dependentAPIs: {}     
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: 
    - name: metrics
      apitype: prometheus
      implementation: {{.Release.Name}}-{{.Values.component.name}}-sm
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000    
  security:
    controllerRole: {{ .Values.security.controllerRole }}
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    partyrole:
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      implementation: {{.Release.Name}}-partyroleapi
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      port: 8080